# Generated by Django 2.2 on 2019-05-02 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='To do text')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Task status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Time when task created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last time when task updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
